apiVersion: v2
name: common
description: A Helm chart for Kubewekend's application
type: application
version: 0.1.3
appVersion: "1.0.0"
maintainers:
  - name: Xeus Nguyen
    email: xeusnguyen@gmail.com
    url: https://wiki.xeusnguyen.xyz