enabled: true
replicaCount: 1
fullnameOverride: "kubewekend-todo-application"
image:
  repository: "xeusnguyen/application"
  pullPolicy: IfNotPresent
  tag: "v0.0.1"
imagePullSecrets: []
command: ["/bin/sh", "-c"]
runtimeArgs: ["yarn run dev"]
service:
  enabled: true
  port: 3000
  headless: false
volumeMounts: []
volumes: []
serviceAccount:
  create: true
  name: kubewekend-sc
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
rbac:
  create: false
probes:
  disableProbes: ["all"]
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "todo.local"
      paths:
        - path: /
          pathType: ImplementationSpecific
testConnection: false
pdb:
  create: true
  minAvailable: 1
  maxUnavailable: 0
podAnnotations:
  test-annotation: "true"
vault:
  enabled: false
  # These value are only required when `template.type = annotation`
  config:
    path: "secret/data/project" # vault secret path
    role: "vault-role"        # vault k8s auth role
    serviceServer: "https://vault.svc.cluster.local:8200" # vault server address
    namespace: "default" # vault namespace
    # Auth method to use for Vault Agent sidecar
    # Options: kubernetes | token | etc (see https://developer.hashicorp.com/vault/docs/auth)
    authPath: "auth/kubernetes" # default kubernetes
  template:
    name: "config.env" # file name to store the secret data
    # Export file format following the contents rendering with vault values
    content: |
      {{ with secret "secret/data/project" }}
      {{- range $key, $value := .Data.data }}
      export {{ $key }}={{ $value }}
      {{- end }}
      {{- end }}