apiVersion: v2
name: cert-manager
description: Cert Manager Infrastructure Chart
type: application
version: 1.0.0
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.19.2