# Default values for cert-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cert-manager:
  installCRDs: true
  prometheus:
    enabled: false

# -- List of ClusterIssuers to create
clusterIssuers: []
  # - name: letsencrypt-staging
  #   spec:
  #     acme:
  #       email: user@example.com
  #       server: https://acme-staging-v02.api.letsencrypt.org/directory
  #       privateKeySecretRef:
  #         name: letsencrypt-staging
  #       solvers:
  #       - http01:
  #           ingress:
  #             class: traefik