{{- if and .Values.pdb.create ( .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" ) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
    {{- with .Values.pdb.minAvailable }}
    minAvailable: {{ . }}
    {{- end }}
    {{- with .Values.pdb.maxUnavailable }}
    maxUnavailable: {{ . }}
    {{- end }}
    selector:
      matchLabels:
        {{- include "common.labels" . | nindent 8 }}
{{- end }}